# Generated by Django 6.0 on 2025-12-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_alter_organizationmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Project',
                'indexes': [models.Index(fields=['organization', 'is_archived'], name='project_pro_organiz_2a8ca3_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_project_per_organization')],
            },
        ),
    ]
