# Generated by Django 6.0 on 2025-12-23 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'name'], name='organizatio_slug_c6b87c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDisplay',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Display',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organization.organization',),
        ),
    ]
